import {
  User,
  Terminal,
  PreparationStation,
  Category,
  ModifierGroup,
  Product,
  Ingredient,
  Recipe,
  Supplier,
  SystemSettings,
  CashierShift,
  CashDrawerTransaction,
  Order,
  InventoryMovement,
  Expense,
  Purchase,
  PrinterJob,
  AuditLog,
  HeldOrder,
  PrinterConfig,
  Employee,
  EmployeePayment,
  EmployeeRateHistory,
  LoyaltySettingHistory,
  Customer,
  StockRequest,
} from '@/types';

export interface DatabaseSchema {
  users: User[];
  terminals: Terminal[];
  stations: PreparationStation[];
  categories: Category[];
  modifierGroups: ModifierGroup[];
  products: Product[];
  ingredients: Ingredient[];
  recipes: Recipe[];
  suppliers: Supplier[];
  settings: SystemSettings;
  shifts: CashierShift[];
  activeShift: CashierShift | null;
  drawerTransactions: CashDrawerTransaction[];
  orders: Order[];
  customers: Customer[];
  inventoryMovements: InventoryMovement[];
  stockRequests: StockRequest[];
  expenses: Expense[];
  purchases: Purchase[];
  employees: Employee[];
  employeePayments: EmployeePayment[];
  rateHistories: EmployeeRateHistory[];
  loyaltyHistories: LoyaltySettingHistory[];
  printerJobs: PrinterJob[];
  printers: PrinterConfig[];
  auditLogs: AuditLog[];
  heldOrders: HeldOrder[];
  nextOrderNumber: number;
  nextHoldNumber: number;
}

export const INITIAL_DATABASE: DatabaseSchema = {
  stockRequests: [],
  users: [
    {
      id: 'usr_admin',
      name: 'Chaminda Silva',
      username: 'admin',
      role: 'ADMIN',
      pin: '1234',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      active: true,
      lastLoginAt: '2026-08-25T07:00:00.000Z',
    },
    {
      id: 'usr_cashier',
      name: 'Nimal Perera',
      username: 'cashier',
      role: 'CASHIER',
      pin: '1111',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      active: true,
      lastLoginAt: '2026-08-25T08:00:00.000Z',
    },
  ],

  terminals: [
    {
      id: 'term_01',
      name: 'Main Counter POS-01',
      code: 'POS-01',
      location: 'Ground Floor Counter',
      isActive: true,
    },
    {
      id: 'term_02',
      name: 'Dessert Bar POS-02',
      code: 'POS-02',
      location: 'Patio & Dessert Counter',
      isActive: false,
    },
  ],

  stations: [
    {
      id: 'st_bar',
      name: 'Coffee & Beverage Bar',
      code: 'BAR',
      printerName: 'Bar Thermal 80mm',
    },
    {
      id: 'st_dessert',
      name: 'Dessert & Waffle Station',
      code: 'DESSERT',
      printerName: 'Dessert Station 80mm',
    },
    {
      id: 'st_kitchen',
      name: 'Hot Kitchen & Bites',
      code: 'KITCHEN',
      printerName: 'Kitchen Thermal 80mm',
    },
  ],

  categories: [
    {
      id: 'cat_coffee',
      name: 'Coffee',
      slug: 'coffee',
      icon: 'Coffee',
      displayOrder: 1,
      preparationStationId: 'st_bar',
      active: true,
    },
    {
      id: 'cat_cold_drinks',
      name: 'Cold Drinks',
      slug: 'cold-drinks',
      icon: 'CupSoda',
      displayOrder: 2,
      preparationStationId: 'st_bar',
      active: true,
    },
    {
      id: 'cat_desserts',
      name: 'Desserts',
      slug: 'desserts',
      icon: 'Cake',
      displayOrder: 3,
      preparationStationId: 'st_dessert',
      active: true,
    },
    {
      id: 'cat_ice_cream',
      name: 'Ice Cream',
      slug: 'ice-cream',
      icon: 'IceCream',
      displayOrder: 4,
      preparationStationId: 'st_dessert',
      active: true,
    },
    {
      id: 'cat_food',
      name: 'Food & Bites',
      slug: 'food',
      icon: 'UtensilsCrossed',
      displayOrder: 5,
      preparationStationId: 'st_kitchen',
      active: true,
    },
    {
      id: 'cat_addons',
      name: 'Add-ons',
      slug: 'addons',
      icon: 'Sparkles',
      displayOrder: 6,
      preparationStationId: 'st_bar',
      active: true,
    },
  ],

  modifierGroups: [
    {
      id: 'mod_size',
      name: 'Size',
      required: true,
      multiSelect: false,
      minSelections: 1,
      maxSelections: 1,
      options: [
        { id: 'opt_sz_reg', name: 'Regular (8oz)', priceCents: 0, isDefault: true },
        { id: 'opt_sz_med', name: 'Medium (12oz)', priceCents: 10000 },
        { id: 'opt_sz_lrg', name: 'Large (16oz)', priceCents: 20000 },
      ],
    },
    {
      id: 'mod_milk',
      name: 'Milk Choice',
      required: false,
      multiSelect: false,
      minSelections: 0,
      maxSelections: 1,
      options: [
        { id: 'opt_milk_fresh', name: 'Fresh Milk', priceCents: 0, isDefault: true },
        { id: 'opt_milk_oat', name: 'Oat Milk', priceCents: 15000 },
        { id: 'opt_milk_almond', name: 'Almond Milk', priceCents: 18000 },
        { id: 'opt_milk_soy', name: 'Soy Milk', priceCents: 12000 },
      ],
    },
    {
      id: 'mod_extras_coffee',
      name: 'Coffee Extras',
      required: false,
      multiSelect: true,
      minSelections: 0,
      maxSelections: 4,
      options: [
        { id: 'opt_ext_shot', name: 'Extra Espresso Shot', priceCents: 20000 },
        { id: 'opt_ext_vanilla', name: 'Vanilla Syrup', priceCents: 10000 },
        { id: 'opt_ext_caramel', name: 'Caramel Drizzle', priceCents: 12000 },
        { id: 'opt_ext_whip', name: 'Whipped Cream', priceCents: 15000 },
      ],
    },
    {
      id: 'mod_sugar',
      name: 'Sweetness',
      required: false,
      multiSelect: false,
      minSelections: 0,
      maxSelections: 1,
      options: [
        { id: 'opt_sug_norm', name: 'Normal Sweet', priceCents: 0, isDefault: true },
        { id: 'opt_sug_less', name: 'Less Sweet (50%)', priceCents: 0 },
        { id: 'opt_sug_none', name: 'No Sugar', priceCents: 0 },
      ],
    },
    {
      id: 'mod_ice',
      name: 'Ice Level',
      required: false,
      multiSelect: false,
      minSelections: 0,
      maxSelections: 1,
      options: [
        { id: 'opt_ice_norm', name: 'Regular Ice', priceCents: 0, isDefault: true },
        { id: 'opt_ice_less', name: 'Less Ice', priceCents: 0 },
        { id: 'opt_ice_none', name: 'No Ice', priceCents: 0 },
      ],
    },
    {
      id: 'mod_toppings_dessert',
      name: 'Dessert Toppings',
      required: false,
      multiSelect: true,
      minSelections: 0,
      maxSelections: 4,
      options: [
        { id: 'opt_top_nutella', name: 'Nutella Drizzle', priceCents: 25000 },
        { id: 'opt_top_gelato', name: 'Vanilla Ice Cream Scoop', priceCents: 30000 },
        { id: 'opt_top_cashew', name: 'Roasted Cashews', priceCents: 18000 },
        { id: 'opt_top_oreo', name: 'Crushed Oreos', priceCents: 15000 },
      ],
    },
    {
      id: 'mod_food_options',
      name: 'Preferences',
      required: false,
      multiSelect: true,
      minSelections: 0,
      maxSelections: 4,
      options: [
        { id: 'opt_food_cheese', name: 'Extra Cheddar Cheese', priceCents: 20000 },
        { id: 'opt_food_spicy', name: 'Spicy Mayo Dip', priceCents: 10000 },
        { id: 'opt_food_noonion', name: 'No Onion', priceCents: 0 },
      ],
    },
  ],

  products: [
    {
      id: 'prod_cappuccino',
      name: 'Cappuccino',
      categoryId: 'cat_coffee',
      description: 'Rich dark espresso topped with silky smooth steamed milk and dense chocolate powder dust.',
      image: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=500&auto=format&fit=crop&q=80',
      basePriceCents: 85000, // Rs. 850.00
      costPriceCents: 28000,
      preparationStationId: 'st_bar',
      modifierGroupIds: ['mod_size', 'mod_milk', 'mod_extras_coffee', 'mod_sugar'],
      taxRate: 0,
      active: true,
      isSoldOut: false,
    },
    {
      id: 'prod_latte',
      name: 'Cafe Latte',
      categoryId: 'cat_coffee',
      description: 'Double shot espresso balanced with creamy textured steamed milk and delicate latte art.',
      image: 'https://images.unsplash.com/photo-1534778101976-62847782c213?w=500&auto=format&fit=crop&q=80',
      basePriceCents: 90000, // Rs. 900.00
      costPriceCents: 30000,
      preparationStationId: 'st_bar',
      modifierGroupIds: ['mod_size', 'mod_milk', 'mod_extras_coffee', 'mod_sugar'],
      taxRate: 0,
      active: true,
      isSoldOut: false,
    },
    {
      id: 'prod_americano',
      name: 'Americano',
      categoryId: 'cat_coffee',
      description: 'Bold double espresso pulled over hot water for a clean, rich aromatic coffee taste.',
      image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=500&auto=format&fit=crop&q=80',
      basePriceCents: 70000, // Rs. 700.00
      costPriceCents: 15000,
      preparationStationId: 'st_bar',
      modifierGroupIds: ['mod_size', 'mod_extras_coffee', 'mod_sugar'],
      taxRate: 0,
      active: true,
      isSoldOut: false,
    },
    {
      id: 'prod_mocha',
      name: 'Mocha Delight',
      categoryId: 'cat_coffee',
      description: 'Signature Belgian chocolate blended with espresso, steamed milk, and velvety chocolate swirls.',
      image: 'https://images.unsplash.com/photo-1578314675249-a6910f80cc4e?w=500&auto=format&fit=crop&q=80',
      basePriceCents: 105000, // Rs. 1,050.00
      costPriceCents: 38000,
      preparationStationId: 'st_bar',
      modifierGroupIds: ['mod_size', 'mod_milk', 'mod_extras_coffee', 'mod_sugar'],
      taxRate: 0,
      active: true,
      isSoldOut: false,
    },
    {
      id: 'prod_iced_coffee',
      name: 'Iced Coffee Chill',
      categoryId: 'cat_cold_drinks',
      description: 'Sri Lankan style chilled brewed coffee with condensed milk, fresh milk, and crushed ice.',
      image: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=500&auto=format&fit=crop&q=80',
      basePriceCents: 95000, // Rs. 950.00
      costPriceCents: 31000,
      preparationStationId: 'st_bar',
      modifierGroupIds: ['mod_size', 'mod_milk', 'mod_ice', 'mod_sugar'],
      taxRate: 0,
      active: true,
      isSoldOut: false,
    },
    {
      id: 'prod_hot_chocolate',
      name: 'Hot Chocolate Special',
      categoryId: 'cat_cold_drinks',
      description: 'Warm, thick Belgian chocolate ganache infused in full cream milk with marshmallow topping.',
      image: 'https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?w=500&auto=format&fit=crop&q=80',
      basePriceCents: 85000, // Rs. 850.00
      costPriceCents: 29000,
      preparationStationId: 'st_bar',
      modifierGroupIds: ['mod_size', 'mod_milk', 'mod_extras_coffee'],
      taxRate: 0,
      active: true,
      isSoldOut: true,
    },
    {
      id: 'prod_choc_milkshake',
      name: 'Chocolate Milkshake',
      categoryId: 'cat_cold_drinks',
      description: 'Decadent chocolate gelato blitzed with cold milk, chocolate fudge and whipped cream cloud.',
      image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=500&auto=format&fit=crop&q=80',
      basePriceCents: 110000, // Rs. 1,100.00
      costPriceCents: 39000,
      preparationStationId: 'st_bar',
      modifierGroupIds: ['mod_size', 'mod_extras_coffee'],
      taxRate: 0,
      active: true,
      isSoldOut: false,
    },
    {
      id: 'prod_vanilla_shake',
      name: 'Vanilla Thickshake',
      categoryId: 'cat_cold_drinks',
      description: 'Madagascar vanilla bean ice cream shaken with chilled cream and golden waffle biscuit.',
      image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500&auto=format&fit=crop&q=80',
      basePriceCents: 105000, // Rs. 1,050.00
      costPriceCents: 37000,
      preparationStationId: 'st_bar',
      modifierGroupIds: ['mod_size'],
      taxRate: 0,
      active: true,
      isSoldOut: false,
    },
    {
      id: 'prod_brownie',
      name: 'Chocolate Brownie',
      categoryId: 'cat_desserts',
      description: 'Fudgy, gooey dark chocolate brownie served warm with a crisp crinkle top.',
      image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=500&auto=format&fit=crop&q=80',
      basePriceCents: 75000, // Rs. 750.00
      costPriceCents: 24000,
      preparationStationId: 'st_dessert',
      modifierGroupIds: ['mod_toppings_dessert'],
      taxRate: 0,
      active: true,
      isSoldOut: false,
    },
    {
      id: 'prod_choc_waffle',
      name: 'Chocolate Waffle',
      categoryId: 'cat_desserts',
      description: 'Crispy golden Belgian waffle drizzled with warm Nutella, fresh strawberries and chocolate flakes.',
      image: 'https://images.unsplash.com/photo-1562376552-0d160a2f238d?w=500&auto=format&fit=crop&q=80',
      basePriceCents: 125000, // Rs. 1,250.00
      costPriceCents: 42000,
      preparationStationId: 'st_dessert',
      modifierGroupIds: ['mod_toppings_dessert'],
      taxRate: 0,
      active: true,
      isSoldOut: false,
    },
    {
      id: 'prod_lava_cake',
      name: 'Molten Choc Lava Cake',
      categoryId: 'cat_desserts',
      description: 'Decadent mini cake with a warm flowing liquid chocolate center and cocoa dusting.',
      image: 'https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=500&auto=format&fit=crop&q=80',
      basePriceCents: 135000, // Rs. 1,350.00
      costPriceCents: 48000,
      preparationStationId: 'st_dessert',
      modifierGroupIds: ['mod_toppings_dessert'],
      taxRate: 0,
      active: true,
      isSoldOut: false,
    },
    {
      id: 'prod_sundae',
      name: 'Ice Cream Sundae Chill',
      categoryId: 'cat_ice_cream',
      description: 'Trio of artisan chocolate, vanilla & caramel ice cream scoops layered with nuts and fudge.',
      image: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=500&auto=format&fit=crop&q=80',
      basePriceCents: 110000, // Rs. 1,100.00
      costPriceCents: 35000,
      preparationStationId: 'st_dessert',
      modifierGroupIds: ['mod_toppings_dessert'],
      taxRate: 0,
      active: true,
      isSoldOut: false,
    },
    {
      id: 'prod_sandwich',
      name: 'Chicken Sandwich',
      categoryId: 'cat_food',
      description: 'Tender grilled spiced chicken breast, crispy lettuce, cheddar cheese and herb mayo in toasted bread.',
      image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=500&auto=format&fit=crop&q=80',
      basePriceCents: 135000, // Rs. 1,350.00
      costPriceCents: 52000,
      preparationStationId: 'st_kitchen',
      modifierGroupIds: ['mod_food_options'],
      taxRate: 0,
      active: true,
      isSoldOut: false,
    },
    {
      id: 'prod_fries',
      name: 'French Fries (Large)',
      categoryId: 'cat_food',
      description: 'Golden crispy shoestring potatoes tossed in seasoned sea salt and served with spicy dip.',
      image: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?w=500&auto=format&fit=crop&q=80',
      basePriceCents: 85000, // Rs. 850.00
      costPriceCents: 22000,
      preparationStationId: 'st_kitchen',
      modifierGroupIds: ['mod_food_options'],
      taxRate: 0,
      active: true,
      isSoldOut: false,
    },
    {
      id: 'prod_burger',
      name: 'Crispy Chicken Burger',
      categoryId: 'cat_food',
      description: 'Buttermilk fried chicken patty with melted cheddar, fresh pickles and special house relish.',
      image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500&auto=format&fit=crop&q=80',
      basePriceCents: 165000, // Rs. 1,650.00
      costPriceCents: 65000,
      preparationStationId: 'st_kitchen',
      modifierGroupIds: ['mod_food_options'],
      taxRate: 0,
      active: true,
      isSoldOut: false,
    },
  ],

  ingredients: [
    {
      id: 'ing_coffee_beans',
      name: 'Arabica Espresso Beans',
      sku: 'ING-CFB-01',
      unit: 'kg',
      currentStock: 8.25,
      reorderLevel: 3.0,
      averageCostCents: 650000, // Rs. 6,500/kg
      supplierId: 'sup_ceylon_coffee',
      expiryDate: '2026-11-30',
      active: true,
    },
    {
      id: 'ing_fresh_milk',
      name: 'Fresh Cow Milk',
      sku: 'ING-MLK-01',
      unit: 'L',
      currentStock: 24.5,
      reorderLevel: 10.0,
      averageCostCents: 48000, // Rs. 480/L
      supplierId: 'sup_highland_dairy',
      expiryDate: '2026-09-06',
      active: true,
    },
    {
      id: 'ing_oat_milk',
      name: 'Barista Oat Milk',
      sku: 'ING-MLK-02',
      unit: 'L',
      currentStock: 8.0,
      reorderLevel: 4.0,
      averageCostCents: 120000,
      supplierId: 'sup_highland_dairy',
      expiryDate: '2026-10-15',
      active: true,
    },
    {
      id: 'ing_choc_syrup',
      name: 'Belgian Chocolate Syrup',
      sku: 'ING-CHC-01',
      unit: 'L',
      currentStock: 4.2,
      reorderLevel: 2.0,
      averageCostCents: 210000,
      supplierId: 'sup_choc_lanka',
      expiryDate: '2026-12-31',
      active: true,
    },
    {
      id: 'ing_brownie_mix',
      name: 'Fudge Brownie Slices',
      sku: 'ING-BRW-01',
      unit: 'pcs',
      currentStock: 18,
      reorderLevel: 5,
      averageCostCents: 24000,
      supplierId: 'sup_choc_lanka',
      expiryDate: '2026-09-12',
      active: true,
    },
    {
      id: 'ing_waffle_batter',
      name: 'Belgian Waffle Batter Mix',
      sku: 'ING-WAF-01',
      unit: 'kg',
      currentStock: 5.5,
      reorderLevel: 2.0,
      averageCostCents: 110000,
      supplierId: 'sup_choc_lanka',
      expiryDate: '2026-09-20',
      active: true,
    },
    {
      id: 'ing_vanilla_gelato',
      name: 'Madagascar Vanilla Gelato',
      sku: 'ING-ICM-01',
      unit: 'L',
      currentStock: 12.0,
      reorderLevel: 4.0,
      averageCostCents: 140000,
      supplierId: 'sup_highland_dairy',
      expiryDate: '2026-10-25',
      active: true,
    },
    {
      id: 'ing_chicken_breast',
      name: 'Marinated Chicken Breast',
      sku: 'ING-CHK-01',
      unit: 'kg',
      currentStock: 6.8,
      reorderLevel: 3.0,
      averageCostCents: 185000,
      supplierId: 'sup_farm_poultry',
      expiryDate: '2026-09-04',
      active: true,
    },
    {
      id: 'ing_bread_slices',
      name: 'Artisan Bread Loaf Slices',
      sku: 'ING-BRD-01',
      unit: 'pcs',
      currentStock: 40,
      reorderLevel: 15,
      averageCostCents: 3500,
      supplierId: 'sup_choc_lanka',
      expiryDate: '2026-09-05',
      active: true,
    },
    {
      id: 'ing_potatoes_fries',
      name: 'Cut Fries Potatoes',
      sku: 'ING-POT-01',
      unit: 'kg',
      currentStock: 14.5,
      reorderLevel: 5.0,
      averageCostCents: 65000,
      supplierId: 'sup_farm_poultry',
      expiryDate: '2026-09-18',
      active: true,
    },
  ],

  recipes: [
    {
      id: 'rcp_cappuccino',
      productId: 'prod_cappuccino',
      productName: 'Cappuccino',
      items: [
        { ingredientId: 'ing_coffee_beans', ingredientName: 'Arabica Espresso Beans', quantity: 0.018, unit: 'kg' },
        { ingredientId: 'ing_fresh_milk', ingredientName: 'Fresh Cow Milk', quantity: 0.150, unit: 'L' },
      ],
    },
    {
      id: 'rcp_latte',
      productId: 'prod_latte',
      productName: 'Cafe Latte',
      items: [
        { ingredientId: 'ing_coffee_beans', ingredientName: 'Arabica Espresso Beans', quantity: 0.018, unit: 'kg' },
        { ingredientId: 'ing_fresh_milk', ingredientName: 'Fresh Cow Milk', quantity: 0.220, unit: 'L' },
      ],
    },
    {
      id: 'rcp_americano',
      productId: 'prod_americano',
      productName: 'Americano',
      items: [
        { ingredientId: 'ing_coffee_beans', ingredientName: 'Arabica Espresso Beans', quantity: 0.018, unit: 'kg' },
      ],
    },
    {
      id: 'rcp_brownie',
      productId: 'prod_brownie',
      productName: 'Chocolate Brownie',
      items: [
        { ingredientId: 'ing_brownie_mix', ingredientName: 'Fudge Brownie Slices', quantity: 1, unit: 'pcs' },
        { ingredientId: 'ing_choc_syrup', ingredientName: 'Belgian Chocolate Syrup', quantity: 0.030, unit: 'L' },
      ],
    },
    {
      id: 'rcp_waffle',
      productId: 'prod_choc_waffle',
      productName: 'Chocolate Waffle',
      items: [
        { ingredientId: 'ing_waffle_batter', ingredientName: 'Belgian Waffle Batter Mix', quantity: 0.180, unit: 'kg' },
        { ingredientId: 'ing_choc_syrup', ingredientName: 'Belgian Chocolate Syrup', quantity: 0.050, unit: 'L' },
        { ingredientId: 'ing_vanilla_gelato', ingredientName: 'Madagascar Vanilla Gelato', quantity: 0.060, unit: 'L' },
      ],
    },
    {
      id: 'rcp_sandwich',
      productId: 'prod_sandwich',
      productName: 'Chicken Sandwich',
      items: [
        { ingredientId: 'ing_chicken_breast', ingredientName: 'Marinated Chicken Breast', quantity: 0.120, unit: 'kg' },
        { ingredientId: 'ing_bread_slices', ingredientName: 'Artisan Bread Loaf Slices', quantity: 2, unit: 'pcs' },
      ],
    },
    {
      id: 'rcp_fries',
      productId: 'prod_fries',
      productName: 'French Fries (Large)',
      items: [
        { ingredientId: 'ing_potatoes_fries', ingredientName: 'Cut Fries Potatoes', quantity: 0.250, unit: 'kg' },
      ],
    },
  ],

  suppliers: [
    {
      id: 'sup_ceylon_coffee',
      name: 'Ceylon Coffee Roasters Ltd',
      contactPerson: 'Rohan Wickramasinghe',
      phone: '+94 77 123 4567',
      email: 'sales@ceyloncoffeeroasters.lk',
      address: 'No. 120, Kandy Road, Colombo 03',
      active: true,
    },
    {
      id: 'sup_highland_dairy',
      name: 'Highland Pure Dairy LK',
      contactPerson: 'Sunil Senanayake',
      phone: '+94 71 456 7890',
      email: 'highlandorders@dairy.lk',
      address: 'Dairy Way, Nuwara Eliya',
      active: true,
    },
    {
      id: 'sup_choc_lanka',
      name: 'Choc & Bakers Supplies Lanka',
      contactPerson: 'Fathima Razeen',
      phone: '+94 11 789 0123',
      email: 'orders@chocbakers.lk',
      address: 'No. 45, Baseline Road, Colombo 09',
      active: true,
    },
    {
      id: 'sup_farm_poultry',
      name: 'Fresh Farm Poultry & Agro',
      contactPerson: 'Janaka Bandara',
      phone: '+94 77 987 6543',
      email: 'janaka@freshfarmagro.lk',
      address: 'Agro Zone, Kurunegala',
      active: true,
    },
  ],

  settings: {
    businessName: 'Chill & Choc',
    tagline: 'Cool Vibes, Sweet Bites',
    address: 'No. 42, Galle Road, Colombo 03, Sri Lanka',
    phone: '+94 11 234 5678',
    email: 'hello@chillandchoc.lk',
    currencyCode: 'LKR',
    currencySymbol: 'Rs.',
    decimalPlaces: 2,
    taxRatePercent: 0,
    serviceChargePercent: 0,
    receiptHeader: 'CHILL & CHOC CAFÉ\nCOOL VIBES, SWEET BITES\nColombo 03, Sri Lanka\nTel: +94 11 234 5678',
    receiptFooter: 'Thank you for chilling with us!\nPlease visit us again.\nFollow @chillandchoc.lk',
    autoPrintReceipt: true,
    autoPrintKOT: true,
    receiptCopies: 1,
    receiptCustomization: {
      showLogo: true,
      logoUrl: '/logobg.webp',
      logoWidthPx: 95,
      logoAlignment: 'center',
      businessName: 'Chill & Choc',
      tagline: 'Cool Vibes, Sweet Bites',
      address: 'No. 42, Galle Road, Colombo 03, Sri Lanka',
      phone: '+94 11 234 5678',
      email: 'hello@chillandchoc.lk',
      website: 'www.chillandchoc.lk',
      taxNumber: 'VAT-LK-10928374',
      headerAlignment: 'center',
      dividerStyle: 'dashed',
      paperWidthMm: 80,
      fontFamily: 'mono',
      fontSize: 'normal',
      showOrderNumber: true,
      orderNumberPrefix: 'Order: #',
      showOrderType: true,
      showTableNumber: true,
      showCashierName: true,
      showDateTime: true,
      timeFormat: '12h',
      showCustomerInfo: true,
      itemSpacing: 'normal',
      showModifiers: true,
      showModifierPrices: true,
      showItemNotes: true,
      showUnitPrice: false,
      showSubtotal: true,
      showDiscount: true,
      showServiceCharge: true,
      serviceChargeLabel: 'Service Charge (10%)',
      showTax: false,
      taxLabel: 'VAT (0%)',
      currencySymbol: 'Rs.',
      showPaymentMethod: true,
      showCashBreakdown: true,
      showCardReference: true,
      receiptFooter: 'Thank you for chilling with us!\nPlease visit us again.\nFollow @chillandchoc.lk',
      showSocialHandle: true,
      socialHandle: '@chillandchoc.lk',
      showWifiInfo: false,
      wifiSsid: 'ChillAndChoc_Guest',
      wifiPassword: 'sweetbites2026',
      showDeveloperCredit: true,
      developerCreditText: 'DEVELOPED BY OGO TECHNOLOGY',
      developerContact: 'www.ogotechnology.net • +94 75 930 7059',
    },
    kotCustomization: {
      ticketTitle: 'KITCHEN ORDER TICKET',
      showBrandName: true,
      brandName: 'CHILL & CHOC',
      showOrderType: true,
      showTableNumber: true,
      tableNumberStyle: 'prominent',
      showOrderNumber: true,
      orderNumberPrefix: '#',
      showCashierName: true,
      cashierLabel: 'Staff',
      showDateTime: true,
      timeFormat: '12h',
      showModifiers: true,
      showItemNotes: true,
      highlightNotes: true,
      fontSize: 'normal',
      paperWidthMm: 80,
      dividerStyle: 'dashed',
      showStationRouting: true,
      stationRoutingText: 'Station Routing: BAR / KITCHEN / DESSERT',
      customNote: '',
    },
    requireOpeningCash: true,
    blindShiftClose: true,
    varianceReasonThresholdCents: 10000, // Rs. 100.00
    requireReasonForCashOut: true,
    allowCashierManualCashIn: true,
    allowCashierManualCashOut: true,
    openDrawerAfterCashSale: true,
    defaultTerminalId: 'term_01',
    // Employee Payroll & Rate Defaults
    defaultOvertimeHourlyRateCents: 45000, // Rs. 450.00 / hour
    defaultLeaveDailyRateCents: 250000, // Rs. 2,500.00 / day
    overtimeCalculationMode: 'FIXED_HOURLY',
    overtimeMultiplier: 1.5,
    standardWorkHoursPerDay: 8,
    workingDaysPerMonth: 26,
    leavePolicyNote: 'Standard monthly leave deduction rate: Rs. 2,500.00/day for unpaid absences',
    // Customer Loyalty & Rewards Program Defaults
    loyaltyProgramEnabled: true,
    loyaltyProgramName: 'Chill Club Rewards',
    loyaltySpendPerPointCents: 10000, // Rs. 100 spent = 1 Point
    loyaltyMinSpendToEarnCents: 20000, // Min Rs. 200 bill to earn points
    loyaltyPointRedemptionValueCents: 100, // 1 Point = Rs. 1.00 discount
    loyaltyMinPointsToRedeem: 50, // 50 Points threshold to redeem
    loyaltyMaxRedemptionPercentPerOrder: 50, // Max 50% of bill total payable via points
    loyaltySignupBonusPoints: 25, // 25 Points welcome bonus
    loyaltyBirthdayBonusPoints: 50, // 50 Points birthday bonus
    loyaltyPointsExpiryDays: 365, // 365 Days validity (1 year)
  },

  shifts: [],
  activeShift: null,
  drawerTransactions: [],
  orders: [],
  inventoryMovements: [],
  expenses: [],
  purchases: [],
  employees: [],
  employeePayments: [],
  rateHistories: [
    {
      id: 'rate_hist_001',
      employeeId: 'GLOBAL',
      employeeName: 'Global Policy (All Staff)',
      rateType: 'OVERTIME',
      previousOvertimeRateCents: 40000,
      newOvertimeRateCents: 45000,
      changedBy: 'Admin (Chaminda Silva)',
      reason: 'Mid-year cost of living adjustment and overtime incentive boost',
      effectiveDate: '2026-07-01',
      createdAt: '2026-07-01T08:30:00.000Z',
    },
    {
      id: 'rate_hist_002',
      employeeId: 'GLOBAL',
      employeeName: 'Global Policy (All Staff)',
      rateType: 'LEAVE',
      previousLeaveRateCents: 220000,
      newLeaveRateCents: 250000,
      changedBy: 'Admin (Chaminda Silva)',
      reason: 'Updated daily unpaid leave deduction rate according to standard store policy',
      effectiveDate: '2026-07-01',
      createdAt: '2026-07-01T08:35:00.000Z',
    },
    {
      id: 'rate_hist_003',
      employeeId: 'emp_002',
      employeeName: 'Nimal Perera',
      rateType: 'OVERTIME',
      previousOvertimeRateCents: 45000,
      newOvertimeRateCents: 55000,
      changedBy: 'Admin (Chaminda Silva)',
      reason: 'Special overtime allowance for Head Barista closing shift supervision',
      effectiveDate: '2026-08-01',
      createdAt: '2026-08-01T09:00:00.000Z',
    },
    {
      id: 'rate_hist_004',
      employeeId: 'emp_001',
      employeeName: 'Chaminda Silva',
      rateType: 'ALL',
      previousOvertimeRateCents: 50000,
      newOvertimeRateCents: 65000,
      previousLeaveRateCents: 400000,
      newLeaveRateCents: 460000,
      changedBy: 'System Owner',
      reason: 'Executive management grade annual compensation & overtime adjustment',
      effectiveDate: '2026-06-15',
      createdAt: '2026-06-15T11:00:00.000Z',
    },
    {
      id: 'rate_hist_005',
      employeeId: 'emp_003',
      employeeName: 'Kasun Fernando',
      rateType: 'OVERTIME',
      previousOvertimeRateCents: 40000,
      newOvertimeRateCents: 45000,
      changedBy: 'Admin (Chaminda Silva)',
      reason: 'Completion of 3-month probation period & standard barista rate upgrade',
      effectiveDate: '2026-08-15',
      createdAt: '2026-08-15T14:20:00.000Z',
    },
  ],
  loyaltyHistories: [
    {
      id: 'loyalty_hist_001',
      changeType: 'EARNING_RATE',
      title: 'Spend Rate Update',
      summary: 'Spend: Rs. 150.00 → Rs. 100.00/pt',
      previousSpendPerPointCents: 15000,
      newSpendPerPointCents: 10000,
      changedBy: 'Admin (Chaminda Silva)',
      reason: 'Enhanced reward points multiplier to celebrate café anniversary',
      createdAt: '2026-08-15T14:20:00.000Z',
    },
    {
      id: 'loyalty_hist_002',
      changeType: 'REDEMPTION_VALUE',
      title: 'Point Value Adjustment',
      summary: 'Point Value: Rs. 0.75 → Rs. 1.00/pt',
      previousRedemptionValueCents: 75,
      newRedemptionValueCents: 100,
      changedBy: 'Admin (Chaminda Silva)',
      reason: 'Standardized 1 Point = Rs. 1.00 direct cash discount equivalent',
      createdAt: '2026-08-01T09:00:00.000Z',
    },
    {
      id: 'loyalty_hist_003',
      changeType: 'BONUS_RULES',
      title: 'Signup & Birthday Rewards',
      summary: 'Signup: 10 → 25 pts · Birthday: 25 → 50 pts',
      previousSignupBonusPoints: 10,
      newSignupBonusPoints: 25,
      previousBirthdayBonusPoints: 25,
      newBirthdayBonusPoints: 50,
      changedBy: 'Admin (Chaminda Silva)',
      reason: 'Upgraded welcome gifts and special birthday patron delight perks',
      createdAt: '2026-07-15T11:45:00.000Z',
    },
    {
      id: 'loyalty_hist_004',
      changeType: 'VALIDITY_LIMITS',
      title: 'Redemption Threshold & Validity',
      summary: 'Min Redeem: 100 → 50 pts · Max Coverage: 50%',
      previousMinPointsToRedeem: 100,
      newMinPointsToRedeem: 50,
      previousMaxRedemptionPercent: 50,
      newMaxRedemptionPercent: 50,
      changedBy: 'Admin (Chaminda Silva)',
      reason: 'Lowered minimum redemption threshold for faster customer reward unlocks',
      createdAt: '2026-07-01T08:30:00.000Z',
    },
    {
      id: 'loyalty_hist_005',
      changeType: 'PROGRAM_CONFIG',
      title: 'Loyalty Program Rebranded',
      summary: 'Program Name: Chill Club Rewards · Status: Active',
      previousProgramName: 'Café Rewards',
      newProgramName: 'Chill Club Rewards',
      previousProgramEnabled: true,
      newProgramEnabled: true,
      changedBy: 'System Owner',
      reason: 'Official brand launch of Chill Club Rewards customer loyalty program',
      createdAt: '2026-06-15T10:00:00.000Z',
    },
  ],
  customers: [
    {
      id: 'cust_001',
      customerId: 'CUST-1001',
      name: 'Anuki Fernando',
      phone: '+94 77 123 4567',
      email: 'anuki.f@example.com',
      address: 'No 45, Alfred House Gardens, Colombo 03',
      birthday: '1996-04-12',
      tier: 'GOLD',
      points: 680,
      totalSpentCents: 4820000,
      totalOrders: 14,
      lastVisit: '2026-09-02T10:48:00.000Z',
      createdAt: '2026-01-15T09:00:00.000Z',
      notes: 'Prefers oat milk for coffees. Regular weekend visitor.',
      pointHistory: [
        {
          id: 'pt_001_1',
          customerId: 'cust_001',
          type: 'EARNED',
          points: 23,
          balanceAfter: 680,
          orderNumber: '#1054',
          note: 'Points earned for Order #1054',
          createdAt: '2026-09-02T10:48:00.000Z',
        },
        {
          id: 'pt_001_2',
          customerId: 'cust_001',
          type: 'BIRTHDAY_BONUS',
          points: 50,
          balanceAfter: 657,
          note: 'Happy Birthday Celebration Bonus Gift!',
          createdAt: '2026-04-12T08:00:00.000Z',
        },
        {
          id: 'pt_001_3',
          customerId: 'cust_001',
          type: 'SIGNUP_BONUS',
          points: 25,
          balanceAfter: 25,
          note: 'Welcome signup reward points',
          createdAt: '2026-01-15T09:00:00.000Z',
        },
      ],
    },
    {
      id: 'cust_002',
      customerId: 'CUST-1002',
      name: 'Kavinda Perera',
      phone: '+94 71 890 1234',
      email: 'kavinda.p@example.com',
      address: '22/4, Galle Road, Mount Lavinia',
      birthday: '1992-08-25',
      tier: 'PLATINUM',
      points: 1240,
      totalSpentCents: 8650000,
      totalOrders: 22,
      lastVisit: '2026-09-02T10:30:00.000Z',
      createdAt: '2025-11-20T14:30:00.000Z',
      notes: 'VIP customer. Often orders takeaway iced coffees.',
      pointHistory: [
        {
          id: 'pt_002_1',
          customerId: 'cust_002',
          type: 'EARNED',
          points: 27,
          balanceAfter: 1240,
          orderNumber: '#1053',
          note: 'Points earned for Order #1053',
          createdAt: '2026-09-02T10:30:00.000Z',
        },
        {
          id: 'pt_002_2',
          customerId: 'cust_002',
          type: 'REDEEMED',
          points: -100,
          balanceAfter: 1213,
          orderNumber: '#1038',
          note: 'Redeemed Rs. 100.00 discount on bill',
          createdAt: '2026-08-28T16:20:00.000Z',
        },
      ],
    },
    {
      id: 'cust_003',
      customerId: 'CUST-1003',
      name: 'Saman Jayasinghe',
      phone: '+94 76 345 6789',
      email: 'saman.j@example.com',
      address: '14, Ward Place, Colombo 07',
      birthday: '1988-11-03',
      tier: 'SILVER',
      points: 310,
      totalSpentCents: 2645000,
      totalOrders: 8,
      lastVisit: '2026-09-02T10:12:00.000Z',
      createdAt: '2026-03-10T11:15:00.000Z',
      notes: 'Likes table seating near window.',
    },
    {
      id: 'cust_004',
      customerId: 'CUST-1004',
      name: 'Rashmi Dissanayake',
      phone: '+94 70 567 8901',
      email: 'rashmi.d@example.com',
      address: '78, Duplication Road, Colombo 04',
      birthday: '1998-02-14',
      tier: 'GOLD',
      points: 540,
      totalSpentCents: 3890000,
      totalOrders: 11,
      lastVisit: '2026-09-02T09:45:00.000Z',
      createdAt: '2026-02-01T15:00:00.000Z',
      notes: 'Loves chocolate desserts and matcha specials.',
    },
    {
      id: 'cust_005',
      customerId: 'CUST-1005',
      name: 'Dilshan Silva',
      phone: '+94 77 987 6543',
      email: 'dilshan.silva@example.com',
      address: '5B, Flower Road, Colombo 07',
      birthday: '1995-09-18',
      tier: 'SILVER',
      points: 290,
      totalSpentCents: 2135000,
      totalOrders: 6,
      lastVisit: '2026-09-02T09:20:00.000Z',
      createdAt: '2026-04-05T12:00:00.000Z',
    },
    {
      id: 'cust_006',
      customerId: 'CUST-1006',
      name: 'Praveen Karunaratne',
      phone: '+94 72 456 7890',
      email: 'praveen.k@example.com',
      address: '91, Baseline Road, Colombo 09',
      birthday: '1990-06-30',
      tier: 'PLATINUM',
      points: 980,
      totalSpentCents: 7210000,
      totalOrders: 19,
      lastVisit: '2026-09-02T08:55:00.000Z',
      createdAt: '2025-10-12T16:45:00.000Z',
      notes: 'Always orders double espresso Americano.',
    },
    {
      id: 'cust_007',
      customerId: 'CUST-1007',
      name: 'Shenali Mendis',
      phone: '+94 78 234 5678',
      email: 'shenali.m@example.com',
      address: '10/2, Havelock Road, Colombo 05',
      birthday: '2000-12-05',
      tier: 'BRONZE',
      points: 150,
      totalSpentCents: 1480000,
      totalOrders: 4,
      lastVisit: '2026-09-02T08:35:00.000Z',
      createdAt: '2026-06-18T10:30:00.000Z',
    },
    {
      id: 'cust_008',
      customerId: 'CUST-1008',
      name: 'Dinuka Senanayake',
      phone: '+94 75 678 9012',
      email: 'dinuka.s@example.com',
      address: '84, Kandy Road, Kadawatha',
      birthday: '1994-03-22',
      tier: 'BRONZE',
      points: 85,
      totalSpentCents: 945000,
      totalOrders: 3,
      lastVisit: '2026-09-02T08:15:00.000Z',
      createdAt: '2026-07-02T13:20:00.000Z',
    },
    {
      id: 'cust_009',
      customerId: 'CUST-1009',
      name: 'Malik Jayawardena',
      phone: '+94 77 654 3210',
      email: 'malik.j@example.com',
      address: '18, Gregory Road, Colombo 07',
      birthday: '1991-07-19',
      tier: 'GOLD',
      points: 475,
      totalSpentCents: 3520000,
      totalOrders: 9,
      lastVisit: '2026-09-01T18:30:00.000Z',
      createdAt: '2026-02-22T17:10:00.000Z',
    },
    {
      id: 'cust_010',
      customerId: 'CUST-1010',
      name: 'Gayan Alwis',
      phone: '+94 71 234 5678',
      email: 'gayan.alwis@example.com',
      address: '33, Rajagiriya Road, Rajagiriya',
      birthday: '1997-10-10',
      tier: 'SILVER',
      points: 210,
      totalSpentCents: 1890000,
      totalOrders: 5,
      lastVisit: '2026-09-01T16:15:00.000Z',
      createdAt: '2026-05-11T14:00:00.000Z',
    },
    {
      id: 'cust_011',
      customerId: 'CUST-1011',
      name: 'Niluka Perera',
      phone: '+94 76 789 0123',
      email: 'niluka.p@example.com',
      address: '12, Stanmore Crescent, Colombo 07',
      birthday: '1999-05-15',
      tier: 'BRONZE',
      points: 120,
      totalSpentCents: 1125000,
      totalOrders: 3,
      lastVisit: '2026-09-01T14:10:00.000Z',
      createdAt: '2026-07-15T11:45:00.000Z',
    },
    {
      id: 'cust_012',
      customerId: 'CUST-1012',
      name: 'Anil Dias',
      phone: '+94 70 123 4567',
      email: 'anil.dias@example.com',
      address: '56, Negombo Road, Wattala',
      birthday: '1985-01-28',
      tier: 'BRONZE',
      points: 95,
      totalSpentCents: 860000,
      totalOrders: 2,
      lastVisit: '2026-09-01T11:30:00.000Z',
      createdAt: '2026-08-01T09:30:00.000Z',
    },
  ],
  printerJobs: [],
  printers: [
    {
      id: 'prn_receipt_80mm',
      name: 'Counter Thermal Receipt (POS-01)',
      role: 'RECEIPT',
      connectionType: 'LAN_IP',
      address: '192.168.1.100:9100',
      paperWidthMm: 80,
      autoCut: true,
      drawerKickRJ12: true,
      beepOnPrint: false,
      copies: 1,
      isOnline: true,
      isDefaultReceipt: true,
    },
    {
      id: 'prn_kitchen_80mm',
      name: 'Kitchen KOT Prep Thermal',
      role: 'KITCHEN_KOT',
      connectionType: 'LAN_IP',
      address: '192.168.1.101:9100',
      stationId: 'st_kitchen',
      paperWidthMm: 80,
      autoCut: true,
      drawerKickRJ12: false,
      beepOnPrint: true,
      copies: 1,
      isOnline: true,
      isDefaultReceipt: false,
    },
    {
      id: 'prn_bar_80mm',
      name: 'Bar & Espresso KOT Thermal',
      role: 'BAR_KOT',
      connectionType: 'USB',
      address: 'USB001 (ESC/POS)',
      stationId: 'st_bar',
      paperWidthMm: 80,
      autoCut: true,
      drawerKickRJ12: false,
      beepOnPrint: true,
      copies: 1,
      isOnline: true,
      isDefaultReceipt: false,
    },
    {
      id: 'prn_dessert_80mm',
      name: 'Dessert & Waffle Station Thermal',
      role: 'DESSERT_KOT',
      connectionType: 'BLUETOOTH',
      address: 'BT:CHILL-DESSERT-80',
      stationId: 'st_dessert',
      paperWidthMm: 80,
      autoCut: true,
      drawerKickRJ12: false,
      beepOnPrint: true,
      copies: 1,
      isOnline: true,
      isDefaultReceipt: false,
    },
  ],
  auditLogs: [],
  heldOrders: [],
  nextOrderNumber: 1055,
  nextHoldNumber: 1,
};

/**
 * Generate rich, realistic dummy demo data for Today and recent days.
 * Dynamically synchronizes timestamps to today's local date so charts,
 * today's net sales, hourly velocity, category shares, and orders list
 * are completely populated and look vibrant immediately.
 */
export function generateSampleSeedData(): {
  shifts: CashierShift[];
  activeShift: CashierShift;
  orders: Order[];
  expenses: Expense[];
  drawerTransactions: CashDrawerTransaction[];
  inventoryMovements: InventoryMovement[];
} {
  const now = new Date();
  const todayStr = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')}`;

  const getTimeToday = (hour: number, minute: number = 0) => {
    const d = new Date(now);
    d.setHours(hour, minute, 0, 0);
    return d.toISOString();
  };

  const getTimePastDays = (daysAgo: number, hour: number, minute: number = 0) => {
    const d = new Date(now);
    d.setDate(d.getDate() - daysAgo);
    d.setHours(hour, minute, 0, 0);
    return d.toISOString();
  };

  const shiftIdToday = 'shift_today_01';
  const shiftIdYesterday = 'shift_yesterday_01';

  // 1. DUMMY ORDERS
  const orders: Order[] = [
    {
      id: 'ord_demo_01',
      orderNumber: '#1054',
      numericOrderNum: 1054,
      shiftId: shiftIdToday,
      cashierId: 'usr_cashier',
      cashierName: 'Nimal Perera',
      terminalId: 'term_01',
      orderType: 'DINE_IN',
      tableNumber: '05',
      customerName: 'Anuki Fernando',
      status: 'COMPLETED',
      items: [
        {
          id: 'item_d1_1',
          productId: 'prod_choc_waffle',
          name: 'Belgian Chocolate Waffle',
          basePriceCents: 125000,
          quantity: 1,
          modifiers: [
            { groupId: 'mod_toppings_dessert', groupName: 'Dessert Toppings', optionId: 'opt_top_nutella', optionName: 'Nutella Drizzle', priceCents: 25000 },
          ],
          itemTotalCents: 150000,
          preparationStationId: 'st_dessert',
        },
        {
          id: 'item_d1_2',
          productId: 'prod_cappuccino',
          name: 'Cappuccino',
          basePriceCents: 85000,
          quantity: 1,
          modifiers: [
            { groupId: 'mod_milk', groupName: 'Milk Choice', optionId: 'opt_milk_fresh', optionName: 'Fresh Milk', priceCents: 0 },
          ],
          itemTotalCents: 85000,
          preparationStationId: 'st_bar',
        },
      ],
      subtotalCents: 235000,
      discountCents: 0,
      serviceChargeCents: 0,
      taxCents: 0,
      totalCents: 235000,
      paymentMethod: 'CASH',
      cashReceivedCents: 250000,
      changeGivenCents: 15000,
      isPaid: true,
      kotPrinted: true,
      receiptPrinted: true,
      createdAt: getTimeToday(10, 48),
      completedAt: getTimeToday(10, 48),
    },
    {
      id: 'ord_demo_02',
      orderNumber: '#1053',
      numericOrderNum: 1053,
      shiftId: shiftIdToday,
      cashierId: 'usr_cashier',
      cashierName: 'Nimal Perera',
      terminalId: 'term_01',
      orderType: 'TAKEAWAY',
      customerName: 'Kavinda Perera',
      status: 'COMPLETED',
      items: [
        {
          id: 'item_d2_1',
          productId: 'prod_iced_coffee',
          name: 'Iced Coffee Chill',
          basePriceCents: 95000,
          quantity: 2,
          modifiers: [],
          itemTotalCents: 190000,
          preparationStationId: 'st_bar',
        },
        {
          id: 'item_d2_2',
          productId: 'prod_brownie',
          name: 'Fudge Brownie Slice',
          basePriceCents: 85000,
          quantity: 1,
          modifiers: [],
          itemTotalCents: 85000,
          preparationStationId: 'st_dessert',
        },
      ],
      subtotalCents: 275000,
      discountCents: 0,
      serviceChargeCents: 0,
      taxCents: 0,
      totalCents: 275000,
      paymentMethod: 'CARD',
      cardReference: 'VISA-4412',
      isPaid: true,
      kotPrinted: true,
      receiptPrinted: true,
      createdAt: getTimeToday(10, 30),
      completedAt: getTimeToday(10, 30),
    },
    {
      id: 'ord_demo_03',
      orderNumber: '#1052',
      numericOrderNum: 1052,
      shiftId: shiftIdToday,
      cashierId: 'usr_cashier',
      cashierName: 'Nimal Perera',
      terminalId: 'term_01',
      orderType: 'DINE_IN',
      tableNumber: '02',
      customerName: 'Saman Jayasinghe',
      status: 'COMPLETED',
      items: [
        {
          id: 'item_d3_1',
          productId: 'prod_club_sandwich',
          name: 'Classic Chicken Club Sandwich',
          basePriceCents: 185000,
          quantity: 1,
          modifiers: [],
          itemTotalCents: 185000,
          preparationStationId: 'st_kitchen',
        },
        {
          id: 'item_d3_2',
          productId: 'prod_french_fries',
          name: 'Crispy Seasoned Fries',
          basePriceCents: 85000,
          quantity: 1,
          modifiers: [],
          itemTotalCents: 85000,
          preparationStationId: 'st_kitchen',
        },
        {
          id: 'item_d3_3',
          productId: 'prod_hot_chocolate',
          name: 'Hot Chocolate Special',
          basePriceCents: 85000,
          quantity: 1,
          modifiers: [],
          itemTotalCents: 85000,
          preparationStationId: 'st_bar',
        },
      ],
      subtotalCents: 355000,
      discountCents: 35500,
      discountReason: 'Promo Discount 10%',
      serviceChargeCents: 0,
      taxCents: 0,
      totalCents: 319500,
      paymentMethod: 'CASH',
      cashReceivedCents: 350000,
      changeGivenCents: 30500,
      isPaid: true,
      kotPrinted: true,
      receiptPrinted: true,
      createdAt: getTimeToday(10, 12),
      completedAt: getTimeToday(10, 12),
    },
    {
      id: 'ord_demo_04',
      orderNumber: '#1051',
      numericOrderNum: 1051,
      shiftId: shiftIdToday,
      cashierId: 'usr_cashier',
      cashierName: 'Nimal Perera',
      terminalId: 'term_01',
      orderType: 'DINE_IN',
      tableNumber: '04',
      customerName: 'Rashmi Dissanayake',
      status: 'COMPLETED',
      items: [
        {
          id: 'item_d4_1',
          productId: 'prod_latte',
          name: 'Cafe Latte',
          basePriceCents: 90000,
          quantity: 2,
          modifiers: [
            { groupId: 'mod_milk', groupName: 'Milk Choice', optionId: 'opt_milk_oat', optionName: 'Oat Milk', priceCents: 15000 },
          ],
          itemTotalCents: 210000,
          preparationStationId: 'st_bar',
        },
        {
          id: 'item_d4_2',
          productId: 'prod_choc_lava',
          name: 'Choc Lava Warm Cake',
          basePriceCents: 145000,
          quantity: 1,
          modifiers: [
            { groupId: 'mod_toppings_dessert', groupName: 'Dessert Toppings', optionId: 'opt_top_gelato', optionName: 'Vanilla Ice Cream Scoop', priceCents: 30000 },
          ],
          itemTotalCents: 175000,
          preparationStationId: 'st_dessert',
        },
      ],
      subtotalCents: 385000,
      discountCents: 0,
      serviceChargeCents: 0,
      taxCents: 0,
      totalCents: 385000,
      paymentMethod: 'QR',
      qrReference: 'LQR-20260826-8831',
      isPaid: true,
      kotPrinted: true,
      receiptPrinted: true,
      createdAt: getTimeToday(9, 45),
      completedAt: getTimeToday(9, 45),
    },
    {
      id: 'ord_demo_05',
      orderNumber: '#1050',
      numericOrderNum: 1050,
      shiftId: shiftIdToday,
      cashierId: 'usr_cashier',
      cashierName: 'Nimal Perera',
      terminalId: 'term_01',
      orderType: 'TAKEAWAY',
      customerName: 'Dilshan Silva',
      status: 'COMPLETED',
      items: [
        {
          id: 'item_d5_1',
          productId: 'prod_choc_milkshake',
          name: 'Chocolate Milkshake',
          basePriceCents: 110000,
          quantity: 1,
          modifiers: [],
          itemTotalCents: 110000,
          preparationStationId: 'st_bar',
        },
        {
          id: 'item_d5_2',
          productId: 'prod_vanilla_shake',
          name: 'Vanilla Thickshake',
          basePriceCents: 105000,
          quantity: 1,
          modifiers: [],
          itemTotalCents: 105000,
          preparationStationId: 'st_bar',
        },
      ],
      subtotalCents: 215000,
      discountCents: 0,
      serviceChargeCents: 0,
      taxCents: 0,
      totalCents: 215000,
      paymentMethod: 'CARD',
      cardReference: 'MC-8109',
      isPaid: true,
      kotPrinted: true,
      receiptPrinted: true,
      createdAt: getTimeToday(9, 20),
      completedAt: getTimeToday(9, 20),
    },
    {
      id: 'ord_demo_06',
      orderNumber: '#1049',
      numericOrderNum: 1049,
      shiftId: shiftIdToday,
      cashierId: 'usr_cashier',
      cashierName: 'Nimal Perera',
      terminalId: 'term_01',
      orderType: 'DINE_IN',
      tableNumber: '01',
      customerName: 'Praveen Karunaratne',
      status: 'COMPLETED',
      items: [
        {
          id: 'item_d6_1',
          productId: 'prod_americano',
          name: 'Americano',
          basePriceCents: 70000,
          quantity: 1,
          modifiers: [],
          itemTotalCents: 70000,
          preparationStationId: 'st_bar',
        },
        {
          id: 'item_d6_2',
          productId: 'prod_cappuccino',
          name: 'Cappuccino',
          basePriceCents: 85000,
          quantity: 1,
          modifiers: [],
          itemTotalCents: 85000,
          preparationStationId: 'st_bar',
        },
      ],
      subtotalCents: 155000,
      discountCents: 0,
      serviceChargeCents: 0,
      taxCents: 0,
      totalCents: 155000,
      paymentMethod: 'CASH',
      cashReceivedCents: 200000,
      changeGivenCents: 45000,
      isPaid: true,
      kotPrinted: true,
      receiptPrinted: true,
      createdAt: getTimeToday(8, 55),
      completedAt: getTimeToday(8, 55),
    },
    {
      id: 'ord_demo_07',
      orderNumber: '#1048',
      numericOrderNum: 1048,
      shiftId: shiftIdToday,
      cashierId: 'usr_cashier',
      cashierName: 'Nimal Perera',
      terminalId: 'term_01',
      orderType: 'TAKEAWAY',
      customerName: 'Shenali Mendis',
      status: 'COMPLETED',
      items: [
        {
          id: 'item_d7_1',
          productId: 'prod_mocha',
          name: 'Mocha Delight',
          basePriceCents: 105000,
          quantity: 1,
          modifiers: [],
          itemTotalCents: 105000,
          preparationStationId: 'st_bar',
        },
        {
          id: 'item_d7_2',
          productId: 'prod_cheesecake',
          name: 'New York Blueberry Cheesecake',
          basePriceCents: 135000,
          quantity: 1,
          modifiers: [],
          itemTotalCents: 135000,
          preparationStationId: 'st_dessert',
        },
      ],
      subtotalCents: 240000,
      discountCents: 0,
      serviceChargeCents: 0,
      taxCents: 0,
      totalCents: 240000,
      paymentMethod: 'CASH',
      cashReceivedCents: 250000,
      changeGivenCents: 10000,
      isPaid: true,
      kotPrinted: true,
      receiptPrinted: true,
      createdAt: getTimeToday(8, 35),
      completedAt: getTimeToday(8, 35),
    },
    {
      id: 'ord_demo_08',
      orderNumber: '#1047',
      numericOrderNum: 1047,
      shiftId: shiftIdToday,
      cashierId: 'usr_cashier',
      cashierName: 'Nimal Perera',
      terminalId: 'term_01',
      orderType: 'DINE_IN',
      tableNumber: '03',
      customerName: 'Dinuka Senanayake',
      status: 'REFUNDED',
      refundReason: 'Customer ordered wrong size and re-ordered',
      refundedAmountCents: 85000,
      items: [
        {
          id: 'item_d8_1',
          productId: 'prod_cappuccino',
          name: 'Cappuccino',
          basePriceCents: 85000,
          quantity: 1,
          modifiers: [],
          itemTotalCents: 85000,
          preparationStationId: 'st_bar',
        },
      ],
      subtotalCents: 85000,
      discountCents: 0,
      serviceChargeCents: 0,
      taxCents: 0,
      totalCents: 85000,
      paymentMethod: 'CASH',
      cashReceivedCents: 100000,
      changeGivenCents: 15000,
      isPaid: true,
      kotPrinted: true,
      receiptPrinted: true,
      createdAt: getTimeToday(8, 15),
      completedAt: getTimeToday(8, 15),
    },
    // Historical Orders from Yesterday and Earlier
    {
      id: 'ord_demo_09',
      orderNumber: '#1046',
      numericOrderNum: 1046,
      shiftId: shiftIdYesterday,
      cashierId: 'usr_admin',
      cashierName: 'Chaminda Silva',
      terminalId: 'term_01',
      orderType: 'DINE_IN',
      tableNumber: '06',
      customerName: 'Malik Jayawardena',
      status: 'COMPLETED',
      items: [
        {
          id: 'item_d9_1',
          productId: 'prod_chicken_burger',
          name: 'Crispy Gourmet Chicken Burger',
          basePriceCents: 165000,
          quantity: 2,
          modifiers: [],
          itemTotalCents: 330000,
          preparationStationId: 'st_kitchen',
        },
        {
          id: 'item_d9_2',
          productId: 'prod_iced_coffee',
          name: 'Iced Coffee Chill',
          basePriceCents: 95000,
          quantity: 2,
          modifiers: [],
          itemTotalCents: 190000,
          preparationStationId: 'st_bar',
        },
      ],
      subtotalCents: 520000,
      discountCents: 0,
      serviceChargeCents: 0,
      taxCents: 0,
      totalCents: 520000,
      paymentMethod: 'CARD',
      cardReference: 'VISA-9021',
      isPaid: true,
      kotPrinted: true,
      receiptPrinted: true,
      createdAt: getTimePastDays(1, 18, 30),
      completedAt: getTimePastDays(1, 18, 30),
    },
    {
      id: 'ord_demo_10',
      orderNumber: '#1045',
      numericOrderNum: 1045,
      shiftId: shiftIdYesterday,
      cashierId: 'usr_admin',
      cashierName: 'Chaminda Silva',
      terminalId: 'term_01',
      orderType: 'DINE_IN',
      tableNumber: '05',
      customerName: 'Gayan Alwis',
      status: 'COMPLETED',
      items: [
        {
          id: 'item_d10_1',
          productId: 'prod_sundae',
          name: 'Signature Chocolate Brownie Sundae',
          basePriceCents: 160000,
          quantity: 2,
          modifiers: [],
          itemTotalCents: 320000,
          preparationStationId: 'st_dessert',
        },
      ],
      subtotalCents: 320000,
      discountCents: 0,
      serviceChargeCents: 0,
      taxCents: 0,
      totalCents: 320000,
      paymentMethod: 'CASH',
      cashReceivedCents: 500000,
      changeGivenCents: 180000,
      isPaid: true,
      kotPrinted: true,
      receiptPrinted: true,
      createdAt: getTimePastDays(1, 16, 15),
      completedAt: getTimePastDays(1, 16, 15),
    },
    {
      id: 'ord_demo_11',
      orderNumber: '#1044',
      numericOrderNum: 1044,
      shiftId: shiftIdYesterday,
      cashierId: 'usr_admin',
      cashierName: 'Chaminda Silva',
      terminalId: 'term_01',
      orderType: 'TAKEAWAY',
      customerName: 'Niluka Perera',
      status: 'COMPLETED',
      items: [
        {
          id: 'item_d11_1',
          productId: 'prod_latte',
          name: 'Cafe Latte',
          basePriceCents: 90000,
          quantity: 3,
          modifiers: [],
          itemTotalCents: 270000,
          preparationStationId: 'st_bar',
        },
      ],
      subtotalCents: 270000,
      discountCents: 0,
      serviceChargeCents: 0,
      taxCents: 0,
      totalCents: 270000,
      paymentMethod: 'QR',
      qrReference: 'LQR-20260825-1022',
      isPaid: true,
      kotPrinted: true,
      receiptPrinted: true,
      createdAt: getTimePastDays(1, 14, 10),
      completedAt: getTimePastDays(1, 14, 10),
    },
    {
      id: 'ord_demo_12',
      orderNumber: '#1043',
      numericOrderNum: 1043,
      shiftId: shiftIdYesterday,
      cashierId: 'usr_admin',
      cashierName: 'Chaminda Silva',
      terminalId: 'term_01',
      orderType: 'DINE_IN',
      tableNumber: '02',
      customerName: 'Anil Dias',
      status: 'COMPLETED',
      items: [
        {
          id: 'item_d12_1',
          productId: 'prod_choc_lava',
          name: 'Choc Lava Warm Cake',
          basePriceCents: 145000,
          quantity: 2,
          modifiers: [],
          itemTotalCents: 290000,
          preparationStationId: 'st_dessert',
        },
      ],
      subtotalCents: 290000,
      discountCents: 0,
      serviceChargeCents: 0,
      taxCents: 0,
      totalCents: 290000,
      paymentMethod: 'CASH',
      cashReceivedCents: 300000,
      changeGivenCents: 10000,
      isPaid: true,
      kotPrinted: true,
      receiptPrinted: true,
      createdAt: getTimePastDays(1, 11, 45),
      completedAt: getTimePastDays(1, 11, 45),
    },
  ];

  // 2. DUMMY OPERATING EXPENSES
  const expenses: Expense[] = [
    {
      id: 'exp_demo_01',
      category: 'EMERGENCY_MILK',
      title: 'Emergency Fresh Barista Milk (4 Litres)',
      amountCents: 240000, // Rs. 2,400.00
      paidViaDrawer: true,
      shiftId: shiftIdToday,
      cashierId: 'usr_cashier',
      cashierName: 'Nimal Perera',
      createdAt: getTimeToday(9, 15),
    },
    {
      id: 'exp_demo_02',
      category: 'EMERGENCY_MILK',
      title: 'Fresh Mint Leaves & Lemons',
      amountCents: 75000, // Rs. 750.00
      paidViaDrawer: true,
      shiftId: shiftIdToday,
      cashierId: 'usr_cashier',
      cashierName: 'Nimal Perera',
      createdAt: getTimeToday(10, 0),
    },
    {
      id: 'exp_demo_03',
      category: 'CLEANING',
      title: 'Table Sanitizer & Paper Napkins Pack',
      amountCents: 120000, // Rs. 1,200.00
      paidViaDrawer: true,
      shiftId: shiftIdToday,
      cashierId: 'usr_cashier',
      cashierName: 'Nimal Perera',
      createdAt: getTimeToday(8, 40),
    },
    {
      id: 'exp_demo_04',
      category: 'PETTY_CASH',
      title: 'Crushed Ice Bags for Cold Beverage Bar',
      amountCents: 60000, // Rs. 600.00
      paidViaDrawer: true,
      shiftId: shiftIdToday,
      cashierId: 'usr_cashier',
      cashierName: 'Nimal Perera',
      createdAt: getTimeToday(8, 25),
    },
    {
      id: 'exp_demo_05',
      category: 'PETTY_CASH',
      title: 'Courier & Emergency Sugar Delivery',
      amountCents: 150000, // Rs. 1,500.00
      paidViaDrawer: true,
      shiftId: shiftIdYesterday,
      cashierId: 'usr_admin',
      cashierName: 'Chaminda Silva',
      createdAt: getTimePastDays(1, 15, 30),
    },
  ];

  // 3. CASH DRAWER TRANSACTIONS
  const drawerTransactions: CashDrawerTransaction[] = [
    {
      id: 'txn_demo_01',
      shiftId: shiftIdToday,
      terminalId: 'term_01',
      cashierId: 'usr_cashier',
      cashierName: 'Nimal Perera',
      type: 'OPENING_CASH',
      amount: 1000000, // Rs. 10,000.00
      balanceAfter: 1000000,
      reason: 'Opening Shift Float',
      timestamp: getTimeToday(8, 0),
    },
    {
      id: 'txn_demo_02',
      shiftId: shiftIdToday,
      terminalId: 'term_01',
      cashierId: 'usr_cashier',
      cashierName: 'Nimal Perera',
      type: 'CASH_OUT',
      amount: -60000, // Rs. 600.00
      balanceAfter: 940000,
      reason: 'Crushed Ice Bags for Cold Beverage Bar',
      expenseCategory: 'PETTY_CASH',
      timestamp: getTimeToday(8, 25),
    },
    {
      id: 'txn_demo_03',
      shiftId: shiftIdToday,
      terminalId: 'term_01',
      cashierId: 'usr_cashier',
      cashierName: 'Nimal Perera',
      type: 'CASH_SALE',
      amount: 240000,
      balanceAfter: 1180000,
      orderNumber: '#1048',
      orderId: 'ord_demo_07',
      timestamp: getTimeToday(8, 35),
    },
    {
      id: 'txn_demo_04',
      shiftId: shiftIdToday,
      terminalId: 'term_01',
      cashierId: 'usr_cashier',
      cashierName: 'Nimal Perera',
      type: 'CASH_OUT',
      amount: -120000,
      balanceAfter: 1060000,
      reason: 'Table Sanitizer & Paper Napkins Pack',
      expenseCategory: 'CLEANING',
      timestamp: getTimeToday(8, 40),
    },
    {
      id: 'txn_demo_05',
      shiftId: shiftIdToday,
      terminalId: 'term_01',
      cashierId: 'usr_cashier',
      cashierName: 'Nimal Perera',
      type: 'CASH_SALE',
      amount: 155000,
      balanceAfter: 1215000,
      orderNumber: '#1049',
      orderId: 'ord_demo_06',
      timestamp: getTimeToday(8, 55),
    },
    {
      id: 'txn_demo_06',
      shiftId: shiftIdToday,
      terminalId: 'term_01',
      cashierId: 'usr_cashier',
      cashierName: 'Nimal Perera',
      type: 'CASH_OUT',
      amount: -240000,
      balanceAfter: 975000,
      reason: 'Emergency Fresh Barista Milk (4 Litres)',
      expenseCategory: 'EMERGENCY_MILK',
      timestamp: getTimeToday(9, 15),
    },
    {
      id: 'txn_demo_07',
      shiftId: shiftIdToday,
      terminalId: 'term_01',
      cashierId: 'usr_cashier',
      cashierName: 'Nimal Perera',
      type: 'CASH_OUT',
      amount: -75000,
      balanceAfter: 900000,
      reason: 'Fresh Mint Leaves & Lemons',
      expenseCategory: 'EMERGENCY_MILK',
      timestamp: getTimeToday(10, 0),
    },
    {
      id: 'txn_demo_08',
      shiftId: shiftIdToday,
      terminalId: 'term_01',
      cashierId: 'usr_cashier',
      cashierName: 'Nimal Perera',
      type: 'CASH_SALE',
      amount: 319500,
      balanceAfter: 1219500,
      orderNumber: '#1052',
      orderId: 'ord_demo_03',
      timestamp: getTimeToday(10, 12),
    },
    {
      id: 'txn_demo_09',
      shiftId: shiftIdToday,
      terminalId: 'term_01',
      cashierId: 'usr_cashier',
      cashierName: 'Nimal Perera',
      type: 'CASH_SALE',
      amount: 235000,
      balanceAfter: 1454500,
      orderNumber: '#1054',
      orderId: 'ord_demo_01',
      timestamp: getTimeToday(10, 48),
    },
  ];

  // 4. SHIFTS
  const activeShift: CashierShift = {
    id: shiftIdToday,
    shiftNumber: 1,
    cashierId: 'usr_cashier',
    cashierName: 'Nimal Perera',
    terminalId: 'term_01',
    terminalName: 'Main Counter POS-01',
    businessDate: todayStr,
    openedAt: getTimeToday(8, 0),
    openingCash: 1000000, // Rs. 10,000.00
    cashSales: 949500, // Rs. 9,495.00
    cardSales: 490000, // Rs. 4,900.00
    qrSales: 385000,   // Rs. 3,850.00
    cashIn: 0,
    cashOut: 495000,   // Rs. 4,950.00
    cashRefunds: 85000,
    cashDrops: 0,
    status: 'OPEN',
  };

  const yesterdayShift: CashierShift = {
    id: shiftIdYesterday,
    shiftNumber: 0,
    cashierId: 'usr_admin',
    cashierName: 'Chaminda Silva',
    terminalId: 'term_01',
    terminalName: 'Main Counter POS-01',
    businessDate: getTimePastDays(1, 0, 0).split('T')[0],
    openedAt: getTimePastDays(1, 8, 0),
    closedAt: getTimePastDays(1, 21, 30),
    openingCash: 1000000,
    closingCashEntered: 1850000,
    expectedClosingCash: 1850000,
    cashSales: 610000,
    cardSales: 520000,
    qrSales: 270000,
    cashIn: 0,
    cashOut: 150000,
    cashRefunds: 0,
    cashDrops: 0,
    variance: 0,
    varianceStatus: 'BALANCED',
    status: 'CLOSED',
  };

  // 5. INVENTORY MOVEMENTS
  const inventoryMovements: InventoryMovement[] = [
    {
      id: 'mov_demo_01',
      ingredientId: 'ing_beans',
      ingredientName: 'Specialty Espresso Beans',
      type: 'PURCHASE',
      quantity: 10,
      unit: 'kg',
      costCents: 4500000,
      reason: 'Batch supplier purchase',
      timestamp: getTimePastDays(2, 9, 0),
    },
    {
      id: 'mov_demo_02',
      ingredientId: 'ing_milk',
      ingredientName: 'Fresh Whole Barista Milk',
      type: 'PURCHASE',
      quantity: 50,
      unit: 'L',
      costCents: 2750000,
      reason: 'Dairy fresh restock',
      timestamp: getTimePastDays(1, 7, 30),
    },
    {
      id: 'mov_demo_03',
      ingredientId: 'ing_choc_chips',
      ingredientName: 'Belgian Dark Choc Ganache',
      type: 'PURCHASE',
      quantity: 15,
      unit: 'kg',
      costCents: 5250000,
      reason: 'Choc confectionery intake',
      timestamp: getTimePastDays(2, 10, 15),
    },
    {
      id: 'mov_demo_04',
      ingredientId: 'ing_milk',
      ingredientName: 'Fresh Whole Barista Milk',
      type: 'SALE_CONSUMPTION',
      quantity: 4.8,
      unit: 'L',
      costCents: 264000,
      reason: 'POS orders automatic usage',
      timestamp: getTimeToday(10, 0),
    },
  ];

  return {
    shifts: [activeShift, yesterdayShift],
    activeShift,
    orders,
    expenses,
    drawerTransactions,
    inventoryMovements,
  };
}

